### ISSUE TITLE
Can't download long videos.

### ISSUE THREAD

**Issue by AzimsLives** [ExploiTR/YouP3#1]
Please enable support for downloading longer youtube audio. I use this app to download youtube podcasts.

**Comment by ExploiTR** [comment]
Sorry @AzimsLives  for this late reply. Actually I'm much busy with studies much due to upcoming exam.

I also use this app to download audios from YouTube. And, yes I am thinking about this issue from a longer time. Actually, this app uses API Service to download audios - so, if the server doesn't sends API response for Youp3's request, YouP3 won't be able to do anything.

And many thanks for using my app and opening an issue. I **will increase** my effort to fix this ASAP (I don't think too soon, but I will try to combine all of my knowledge).

Keep an eye on the future releases.

**Comment by ExploiTR** [comment]
I'm thinking to use [this library](https://github.com/coolguruji/youtube-to-mp3-api) to make that. But it's still in beta, and I need a server(That can be achieved easily but compromising with download speed 👎  ). ~~

**Comment by ExploiTR** [comment]
Okay, got a way 👍 🥇 . Focus on the next version

**Comment by ExploiTR** [comment]
It's ready. I'm testing it. Hope that, I shall be able to release it tomorrow.

**Comment by ExploiTR** [comment]
I've found a serious bug of memory management in YouP3 . I don't think I shall be able to make it up in 5 days.

**Comment by ExploiTR** [comment]
GET : https://github.com/ExploiTR/YouP3/releases/tag/V17.08.2017
